name: Deploy to Prod

on:
  push:
    branches:
      - test

jobs:
  deploy:
    name: Deploy to Prod Account
    runs-on: ubuntu-latest

    permissions:
      id-token: write  
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TEST }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Auth Stack
        env:
          ACCOUNT_ID: "007326679429"
          CI: true      
        run: |
          chmod +x ./deploy-job-offer-admin.sh ./zip-all-lambdas.sh
          ./deploy-job-offer-admin.sh alpha